export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'
export const POST_CREATE_RESET = 'POST_CREATE_RESET'

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL'

export const POST_DONATION_DATE_REQUEST = 'POST_DONATION_DATE_REQUEST'
export const POST_DONATION_DATE_SUCCESS = 'POST_DONATION_DATE_SUCCESS'
export const POST_DONATION_DATE_FAIL = 'POST_DONATION_DATE_FAIL'
export const POST_DONATION_DATE_RESET = 'POST_DONATION_DATE_RESET'

export const POST_MANAGE_REQUEST = 'POST_MANAGE_REQUEST'
export const POST_MANAGE_SUCCESS = 'POST_MANAGE_SUCCESS'
export const POST_MANAGE_FAIL = 'POST_MANAGE_FAIL'
export const POST_MANAGE_RESET = 'POST_MANAGE_RESET'