export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_ACCEPT_REQUEST = 'USER_ACCEPT_REQUEST'
export const USER_ACCEPT_SUCCESS = 'USER_ACCEPT_SUCCESS'
export const USER_ACCEPT_FAIL = 'USER_ACCEPT_FAIL'
export const USER_ACCEPT_RESET = 'USER_ACCEPT_RESET'

export const USER_REVIEW_REQUEST = 'USER_REVIEW_REQUEST'
export const USER_REVIEW_SUCCESS = 'USER_REVIEW_SUCCESS'
export const USER_REVIEW_FAIL = 'USER_REVIEW_FAIL'
export const USER_REVIEW_RESET = 'USER_REVIEW_RESET'

export const USER_REVIEW_ADD_REQUEST = 'USER_REVIEW_ADD_REQUEST'
export const USER_REVIEW_ADD_SUCCESS = 'USER_REVIEW_ADD_SUCCESS'
export const USER_REVIEW_ADD_FAIL = 'USER_REVIEW_ADD_FAIL'
export const USER_REVIEW_ADD_RESET = 'USER_REVIEW_ADD_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

